name: "migration check"

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main

jobs:
  migration-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - uses: 8BitJonny/gh-get-current-pr@2.1.0
      #   id: pr

      - name: Get updated PR title
        uses: actions/github-script@v6
        id: updated-pr-title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        with:
          result-encoding: string
          script: |
            const bodyMatched = process.env.PR_BODY.match(/## Migration Steps(\n|\r|\r\n)- ./);
            const titleMatched = process.env.PR_TITLE.match(/^\[migration\] (.+)$/);
            if (bodyMatched && !titleMatched) {
              return `[migration] ${process.env.PR_TITLE}`;
            }
            if (!bodyMatched && titleMatched) {
              return titleMatched[1];
            }
            return "";

      - name: Update PR title
        if: steps.updated-pr-title.outputs.result != ''
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: main
          head-branch-regex: ${{ github.event.pull_request.head.ref }}
          title-update-action: replace
          title-template: "${{ steps.updated-pr-title.outputs.result }}"
